# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dfbb0b152d783a474ebd45367282d655ea4d61c7e7cf892ce1d723887ac78c94c98861328b6adfd50d3fcbb8d19f95973289754898724d5ddac65baf5b44b72

test:
  secret_key_base: 82a6cdf8d0755bceacda64a768b8cbe0434cb93d71d7363f341849a8cf69fea32be6ba56a85d37566feeed4810b9ebe506a8fbb1b772298109395b2a81597455

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
